version: '3'

services:

  wppc-server:
    build:
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: WPPC-SERVER
    hostname: WPPC-SERVER
    entrypoint: docker-entrypoint.sh yarn dev
    networks:
      - WPPC-NETWORK
    volumes:
      - ./dados-wppconnect/tokens:/home/node/app/tokens
      - ./dados-wppconnect/userDataDir:/home/node/app/userDataDir    
    tty: true

networks:
  WPPC-NETWORK:
    name: WPPC-NETWORK
    driver: bridge